name: Cypress Visual Tests

on:
  pull_request:
    branches: [ cypress ]

jobs:
  visual-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Run Container
      run: |
        docker build -t my-app-test .
        docker run --rm my-app-test
