# File: .github/workflows/workflow.yml
name: Azure App Service - CriticalPath(Production), Build and deploy Angular app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: CriticalPath   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dist/critical-web/browser'
  NODE_VERSION: '20.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install npm dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli@17

    - name: Print npm and Angular CLI versions
      run: |
        npm --version
        ng --version

    - name: Build the project
      run: ng build --configuration=production --project=critical-web

        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: criticalpath
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_141A2AD38517421A95DBCFBEA38D309B }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
