# File: .github/workflows/workflow.yml
name: Azure App Service - CriticalPath(Production), Build and deploy Angular app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: CriticalPath   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dist/critical-web/browser'
  NODE_VERSION: '20.9.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build
      run: |
        npm install
        npm install -g @angular/cli@17
        ng build
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9C9C1F2165684482989E5267E1CA71E5 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        