# File: .github/workflows/workflow.yml
name: Azure App Service - CriticalPath(Production), Build and deploy Angular app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: CriticalPath   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dist/critical-web/browser'
  NODE_VERSION: '20.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install npm dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli@17.0.0

    - name: Check global Angular CLI version
      run: ng version || true

    - name: Check local Angular CLI version
      run: ./node_modules/.bin/ng --version || true

    - name: Print environment debug information
      run: |
        echo "PATH: $PATH"
        pwd
        ls -l
    - name: List global npm packages
      run: npm list -g --depth 0

    - name: List project npm packages
      run: npm list --depth 0




    - name: Print npm node and Angular CLI versions
      run: |
        node --version
        npm --version
        ng version

    - name: Build the project
      run: ng build --configuration=production --project=critical-web

        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: criticalpath
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_141A2AD38517421A95DBCFBEA38D309B }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
